- hosts: all
  become: yes
  become_user: dzl
  tasks:
    - name: add dzl group
      become_user: root
      group: name=dzl
    - name: allow 'dzl' group to have passwordless sudo
      become_user: root
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%dzl'
        line: '%dzl ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: add dzl user
      become_user: root
      user: name=dzl group=dzl append=yes shell=/bin/bash createhome=yes
    - name: add public key for ssh as dzl
      become_user: root
      authorized_key: user=dzl key='{{ item }}'
      with_file:
        - public_keys/patrick
    - name: make /dzl directory
      become_user: root
      file: path='/dzl/{{ item }}' state=directory owner=dzl group=dzl mode=0755
      with_items:
        - src
        - conf
        - log
        - scripts
    - name: add node apt key
      become_user: root
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    - name: add node apt repo
      become_user: root
      apt_repository: repo='deb https://deb.nodesource.com/node_8.x bionic main' state=present filename=nodejs update_cache=yes
    - name: add chrome apt key
      become_user: root
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
    - name: add chrome apt repo
      become_user: root
      apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' state=present filename=google-chrome update_cache=yes
    - name: install dependencies
      become_user: root
      apt:
        pkg: '{{ packages }}'
        state: present
        update_cache: yes
      vars:
        packages:
          - xvfb
          - nodejs
          - google-chrome-stable
    - name: install npm globals
      become_user: root
      npm: name='{{ item }}' global=yes
      with_items: [yarn, surge]
    - name: setup LH repo
      git: repo=https://github.com/GoogleChrome/lighthouse.git dest=/dzl/src/lighthouse
    - name: setup DZL repo
      git: repo=https://github.com/patrickhulce/dzl-lighthouse.git dest=/dzl/src/dzl
    - name: copy scripts over
      copy: src=files/scripts/ dest=/dzl/scripts mode=0755
    - name: copy templates over
      template: src='templates/{{ item }}' dest='/dzl/{{ item }}'
      with_items:
        - conf/agent-official.config.js
        - conf/agent-branch.config.js
- hosts: masters
  become: yes
  become_user: dzl
  tasks:
    - name: install dependencies
      become_user: root
      apt:
        pkg: '{{ packages }}'
        state: present
        update_cache: yes
      vars:
        packages:
          - python3-mysqldb # required for mysql_user module to work
          - mysql-server
    - name: start the mysql service
      become_user: root
      service: name=mysql state=started enabled=yes
    - name: create mysql user
      become_user: root
      mysql_user:
        name: dzl
        host: '{{ item }}'
        password: 'lighthouse'
        check_implicit_admin: yes
        priv: '*.*:ALL,GRANT'
      with_items:
        - '{{ ansible_default_ipv4.address }}' # allow over internal IP address
        - 127.0.0.1
        - ::1
        - localhost
    - name: create mysql db
      mysql_db: name=dzl_lighthouse state=present login_user=dzl login_password=lighthouse
    - name: setup cron job for agent-run-official
      cron: name='dzl official' job='/usr/bin/flock -n /dzl/log/official.lockfile /dzl/scripts/agent-run-official.sh >> /dzl/log/official.log'
