- hosts: masters
  become: yes
  become_user: dzl
  tasks:
    - name: update DZL repo
      shell: git pull
      args:
        chdir: /dzl/src/dzl
    - name: kill DZL serve jobs
      command: /dzl/scripts/restart-dzl-server.sh
